### ISSUE TITLE
unintroduced use of HEAD~ 

### ISSUE THREAD

**Issue by mawds** [gcapes/git-course#42]
In episode 3, line 233, `HEAD~` is used to get the parent commit.   I don't think this has been introduced at this point, so might be clearer to use the absolute commit id?

```
Notice how HEAD and master point to the same commit. Now checkout a previous commit again, and look at the graph again. We can display, this time specifying that we want to look at --all the history, rather than just up to the current commit.

$ git checkout HEAD~
$ git log --graph --decorate --oneline --all
```

**Comment by gcapes** [comment]
Well spotted @mawds !
I think I usually just talk through this point when I come to it, but it's just as well to have it in the notes too. I don't want to use a commit ID in the notes because it'll be wrong for anyone following along by copying the commands.
