### ISSUE TITLE
Authentication not working properly in G11

### ISSUE THREAD

**Issue by mawds** [gcapes/git-course#48]
This appears to be the same issue as
https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/613

(I've run with export `GCM_TRACE=1` and the error is the same)   

Presumably GCM needs updating on the machines in G11

http://staffnet.manchester.ac.uk/news/display/?id=19679 may be useful

**Comment by mawds** [comment]
deadline this Friday for start of teaching year

**Comment by gcapes** [comment]
Great, thanks David!

**Comment by gcapes** [comment]
Update requested.
